language: node_js
node_js:
  - '0.11'
  - '0.10'
before_install: 
  - npm install -g grunt-cli bower coffee-script
install: 
   - npm install
   - bower install
git:
  submodules: false
branches:
  only:
    - master
    - dev
